# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Contatos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Contatos
  pod 'IQKeyboardManagerSwift', '5.0.0'

  target 'ContatosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContatosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
